### ISSUE TITLE
Is the demo website on stagnet v9 or new v11?

### ISSUE THREAD

**Issue by moneroexamples** [amiuhle/kasisto#50]

**Comment by amiuhle** [comment]
Haven't upgraded yet, will have a look tonight.

**Comment by amiuhle** [comment]
It's synchronizing:

```bash
monerod status --stagenet
# => Height: 269400/275037 (98.0%) on stagenet, mining info unavailable, net hash 15 H/s, v10, up to date, 7(out)+2(in) connections
```
I can't test right now because [Monerujo removed stagenet](https://github.com/m2049r/xmrwallet/issues/528), so let please let me know here if there are any issues.

Edit: I just noticed there's a stagenet wallet. But still, just let me know if there are any problems and I'll look into it. Syncing is at `273400/275046`, on `v11`.

**Comment by moneroexamples** [comment]
Thanks. Its working!
